name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 19 * * 2'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 8
            scala: "2.12"
          - java: 8
            scala: "3"
          - java: 25
            scala: "2.12"
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        java-version: "${{ matrix.java }}"
        distribution: zulu
    - uses: coursier/cache-action@v6
    - uses: sbt/setup-sbt@v1
    - run: sudo apt-get update
    - run: sudo apt-get install graphviz
    - run: sed -i -e 's/classDiagram /classDiagramWrite /g' ./src/sbt-test/sbt-class-diagram/simple/test
    - run: sed -i -e 's/$ pause//g' ./src/sbt-test/sbt-class-diagram/simple/test
    - run: cat ./src/sbt-test/sbt-class-diagram/simple/test
    - run: sbt -v
           "++ ${{matrix.scala}}.x"
           scalafmtSbtCheck
           scalafmtCheckAll
           Test/compile
           test
           scripted
