name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 19 * * 2'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 8
            sbt_version: "1.2.8"
          - java: 8
            sbt_version: "1.3.13"
          - java: 8
            sbt_version: "1.4.9"
          - java: 8
          - java: 21
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: "${{ matrix.java }}"
        distribution: temurin
    - uses: coursier/cache-action@v6
    - run: sudo apt-get update
    - run: sudo apt-get install graphviz
    - run: sed -i -e 's/classDiagram /classDiagramWrite /g' ./src/sbt-test/sbt-class-diagram/simple/test
    - run: sed -i -e 's/$ pause//g' ./src/sbt-test/sbt-class-diagram/simple/test
    - run: cat ./src/sbt-test/sbt-class-diagram/simple/test
    - run: sbt -v $(if [[ "${{matrix.sbt_version}}" != "" ]] ; then echo "^^${{matrix.sbt_version}}" ; fi)
           scalafmtSbtCheck
           "+ scalafmtCheckAll"
           test
           scripted
